"""AI summaries and the evidence that they are grounded.

A summary is never returned on its own. It always travels with the verdict
of the grounding check that examined it, because "this sentence was
produced by a language model" and "this sentence is supported by the
abstract" are different claims, and a research tool must not conflate them.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class GroundingStatus(str, Enum):
    """Outcome of checking a summary against its source abstract."""

    #: Every checkable claim traces back to the abstract.
    GROUNDED = "grounded"
    #: Generated text drifted; the summary shown is a fallback, not the model's.
    UNGROUNDED = "ungrounded"
    #: Nothing to check against — the paper has no abstract.
    UNVERIFIABLE = "unverifiable"

    @property
    def is_trustworthy(self) -> bool:
        return self is GroundingStatus.GROUNDED


class IssueKind(str, Enum):
    """The specific way a summary failed to trace back to its abstract.

    Kept as a closed vocabulary rather than free text so the failures can
    be counted, tested, and shown in the UI as a reason rather than a
    generic warning.
    """

    #: A figure appears in the summary that is nowhere in the abstract.
    FABRICATED_NUMBER = "fabricated_number"
    #: A gene, acronym, or named method the abstract never mentions.
    FABRICATED_ENTITY = "fabricated_entity"
    #: The summary shares too little vocabulary with the abstract.
    LOW_OVERLAP = "low_overlap"
    #: A direction of effect the abstract does not state (or reverses).
    CONTRADICTED_DIRECTION = "contradicted_direction"
    #: A novelty or certainty claim the abstract does not make.
    OVERCLAIM = "overclaim"
    #: Not the 2-3 sentences the prompt asked for.
    FORMAT = "format"


class GroundingIssue(BaseModel):
    """One specific, located reason a summary was not accepted."""

    model_config = {"frozen": True}

    kind: IssueKind
    detail: str = Field(description="Human-readable explanation, safe to show a user.")
    span: str | None = Field(
        default=None, description="The offending text from the summary, if localizable."
    )


class GroundingVerdict(BaseModel):
    """The full result of checking one summary against one abstract."""

    status: GroundingStatus
    issues: list[GroundingIssue] = Field(default_factory=list)
    #: Share of the summary's content words that also occur in the abstract.
    overlap: float = Field(default=0.0, ge=0.0, le=1.0)

    @property
    def passed(self) -> bool:
        return self.status is GroundingStatus.GROUNDED


class SummaryOrigin(str, Enum):
    """Where the text a user is reading actually came from."""

    #: Generated by the language model and passed the grounding check.
    GENERATED = "generated"
    #: Generated, failed, regenerated with the failures fed back, then passed.
    REGENERATED = "regenerated"
    #: Sentences lifted verbatim from the abstract, because generation could
    #: not be grounded or no model was configured. Grounded by construction.
    EXTRACTIVE = "extractive"


class Summary(BaseModel):
    """A paper summary, its provenance, and its grounding verdict."""

    text: str
    origin: SummaryOrigin
    grounding: GroundingVerdict
    model: str = Field(description="Model or method that produced the text.")
    #: Bumped whenever the prompt changes, so the cache cannot serve text
    #: produced by an older instruction set.
    prompt_version: int = 1
    attempts: int = Field(default=1, ge=1, description="Generation attempts made.")
    cached: bool = False
    rejected_for: list[GroundingIssue] = Field(
        default_factory=list,
        description=(
            "Why the first attempt was rejected, kept even when a retry "
            "rescued it. The final verdict says the text shown is sound; "
            "this says what it took to get there."
        ),
    )

    @property
    def is_ai_generated(self) -> bool:
        return self.origin is not SummaryOrigin.EXTRACTIVE


class SummaryReport(BaseModel):
    """Per-search summarization diagnostics.

    Mirrors the source, ranking and clustering reports: a stage that
    degraded must say so rather than leave the UI guessing.
    """

    applied: bool
    model: str | None = None
    summarized: int = 0
    from_cache: int = 0
    regenerated: int = Field(
        default=0, description="Summaries that needed a second attempt to pass."
    )
    fell_back: int = Field(
        default=0, description="Summaries that could not be grounded and were replaced."
    )
    elapsed_ms: int = 0
    reason: str | None = None
