/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and configured sources
         * @description Report liveness plus which connectors this instance has registered.
         *
         *     The source list is part of the health payload because the frontend uses
         *     it to render source filters without hardcoding provider names.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search PubMed, arXiv and Crossref in one query
         * @description Fan out to every source, merge, deduplicate, and report per-source status.
         */
        get: operations["search_api_search_get"];
        put?: never;
        /**
         * Search with a JSON body
         * @description POST variant, for abstract snippets too long to sit in a query string.
         */
        post: operations["search_post_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show how a query would be interpreted
         * @description Expose the query classifier so the UI can show the detected input type.
         */
        get: operations["parse_api_parse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export several papers as a citation file
         * @description Render the selected papers in the requested citation format.
         *
         *     Papers are looked up from the store rather than accepted in the
         *     request body, so a citation can only be produced for a record the
         *     server actually retrieved.
         */
        post: operations["export_many_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a single paper
         * @description Render one paper. A GET so it can be a plain link in the UI.
         */
        get: operations["export_one_api_export__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/formats/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the supported citation formats
         * @description Let the UI build its format picker without hardcoding the list.
         */
        get: operations["list_formats_api_export_formats_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Author
         * @description A paper author.
         *
         *     ``given``/``family`` are kept separate whenever the source provides them
         *     because citation formats (BibTeX, RIS) need the split. ``name`` is the
         *     display form and is always populated.
         */
        Author: {
            /** Name */
            name: string;
            /** Given */
            given: string | null;
            /** Family */
            family: string | null;
            /** Affiliation */
            affiliation: string | null;
        };
        /**
         * ClusteringReport
         * @description Whether clustering ran, and how it went.
         *
         *     Mirrors ``RankingReport``: an enrichment that did not happen is a state
         *     the UI has to render, not an error to swallow. A result set too small
         *     to cluster is normal, not a failure.
         */
        ClusteringReport: {
            /** Applied */
            applied: boolean;
            /** Algorithm */
            algorithm: string | null;
            /**
             * Clusters
             * @default 0
             */
            clusters: number;
            /** Silhouette */
            silhouette: number | null;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Reason
             * @description Why clustering did not run.
             */
            reason: string | null;
        };
        /**
         * EnrichmentReport
         * @description Whether entity extraction ran, and with what model.
         *
         *     Same contract as the ranking and clustering reports: the frontend
         *     renders "entities unavailable" differently from "this paper has none".
         */
        EnrichmentReport: {
            /** Applied */
            applied: boolean;
            /** Model */
            model: string | null;
            /**
             * Entities Found
             * @default 0
             */
            entities_found: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /** Reason */
            reason: string | null;
        };
        /**
         * Entity
         * @description A distinct entity mentioned in a paper, with all its occurrences.
         */
        Entity: {
            /**
             * Text
             * @description Surface form, as it appears in the text.
             */
            text: string;
            label: components["schemas"]["EntityLabel"];
            /**
             * Raw Label
             * @description The label the underlying model emitted.
             */
            raw_label: string;
            /** Spans */
            spans: components["schemas"]["EntitySpan"][];
        };
        /**
         * EntityLabel
         * @description Entity categories, normalized across NER models.
         *
         *     Different models emit wildly different label sets — ``en_core_web_sm``
         *     is trained on news (ORG, PERSON, GPE), while SciSpacy models emit
         *     biomedical types (DISEASE, CHEMICAL, GENE_OR_GENE_PRODUCT). Everything
         *     is mapped onto this enum so the API contract and the UI do not change
         *     when the underlying model does.
         * @enum {string}
         */
        EntityLabel: "gene_or_protein" | "disease" | "chemical" | "organism" | "anatomy" | "cell_type" | "technical_term" | "organization" | "person" | "location" | "other";
        /**
         * EntitySpan
         * @description One occurrence of an entity, as character offsets into a field.
         */
        EntitySpan: {
            /**
             * Field
             * @enum {string}
             */
            field: "title" | "abstract";
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /**
         * ExportFormat
         * @description Formats a user can ask for.
         *
         *     APA and Vancouver are separate members rather than a style parameter
         *     on one member: from the caller's point of view they are two different
         *     things to click, and modelling them as one format with a modifier
         *     pushes that distinction into every caller.
         * @enum {string}
         */
        ExportFormat: "bibtex" | "ris" | "apa" | "vancouver";
        /**
         * ExportRequest
         * @description A bulk export of previously retrieved papers.
         */
        ExportRequest: {
            /** Paper Ids */
            paper_ids: string[];
            /** @default bibtex */
            format: components["schemas"]["ExportFormat"];
            /**
             * Filename
             * @description Base name for the download, without extension.
             */
            filename?: string | null;
        };
        /**
         * GroundingIssue
         * @description One specific, located reason a summary was not accepted.
         */
        GroundingIssue: {
            kind: components["schemas"]["IssueKind"];
            /**
             * Detail
             * @description Human-readable explanation, safe to show a user.
             */
            detail: string;
            /**
             * Span
             * @description The offending text from the summary, if localizable.
             */
            span: string | null;
        };
        /**
         * GroundingStatus
         * @description Outcome of checking a summary against its source abstract.
         * @enum {string}
         */
        GroundingStatus: "grounded" | "ungrounded" | "unverifiable";
        /**
         * GroundingVerdict
         * @description The full result of checking one summary against one abstract.
         */
        GroundingVerdict: {
            status: components["schemas"]["GroundingStatus"];
            /** Issues */
            issues: components["schemas"]["GroundingIssue"][];
            /**
             * Overlap
             * @default 0
             */
            overlap: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App */
            app: string;
            /** Environment */
            environment: string;
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
        };
        /**
         * IdentifierKind
         * @enum {string}
         */
        IdentifierKind: "doi" | "arxiv" | "pmid";
        /**
         * IssueKind
         * @description The specific way a summary failed to trace back to its abstract.
         *
         *     Kept as a closed vocabulary rather than free text so the failures can
         *     be counted, tested, and shown in the UI as a reason rather than a
         *     generic warning.
         * @enum {string}
         */
        IssueKind: "fabricated_number" | "fabricated_entity" | "low_overlap" | "contradicted_direction" | "overclaim" | "format";
        /**
         * Paper
         * @description A single scientific work, normalized across all sources.
         *
         *     Optionality is deliberate and pervasive: real-world records routinely
         *     lack an abstract, a DOI, or a usable publication date, and the pipeline
         *     must degrade gracefully rather than drop those records.
         */
        Paper: {
            /**
             * Id
             * @description Stable fingerprint, derived from DOI or source id.
             */
            id: string;
            /**
             * Doi
             * @description Lowercased, bare DOI (no URL prefix).
             */
            doi: string | null;
            /** @description Provider this record was retrieved from. */
            source: components["schemas"]["SourceName"];
            /**
             * Source Id
             * @description Provider-native identifier (PMID, arXiv id, DOI).
             */
            source_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: components["schemas"]["Author"][];
            /** Abstract */
            abstract: string | null;
            /** Published Date */
            published_date: string | null;
            /** Url */
            url: string;
            /** Journal */
            journal: string | null;
            /** Publisher */
            publisher: string | null;
            /** Volume */
            volume: string | null;
            /** Issue */
            issue: string | null;
            /** Pages */
            pages: string | null;
            /** Publication Type */
            publication_type: string | null;
            /** Keywords */
            keywords: string[];
            /** Pdf Url */
            pdf_url: string | null;
            /** Citation Count */
            citation_count: number | null;
            score: components["schemas"]["RelevanceScore"] | null;
            /** @description AI or extractive summary, carrying its own grounding verdict. */
            summary: components["schemas"]["Summary"] | null;
            /**
             * Entities
             * @description Named entities found in the title and abstract, with spans.
             */
            entities: components["schemas"]["Entity"][];
            /**
             * Cluster Id
             * @description Index of the topic cluster this paper was assigned to.
             */
            cluster_id: number | null;
            /**
             * Also Found In
             * @description Other sources that returned this same work.
             */
            also_found_in: components["schemas"]["SourceName"][];
        };
        /**
         * ParsedQuery
         * @description The user's raw input, interpreted.
         *
         *     ``search_terms`` is what actually gets sent to the upstream APIs: for a
         *     pasted abstract that is a distilled keyword string, because no provider
         *     accepts a paragraph as a query. ``raw`` is preserved untouched because
         *     Stage 2 embeds the full text for semantic ranking.
         */
        ParsedQuery: {
            /** Raw */
            raw: string;
            intent: components["schemas"]["QueryIntent"];
            /** Search Terms */
            search_terms: string;
            identifier_kind: components["schemas"]["IdentifierKind"] | null;
            /** Identifier */
            identifier: string | null;
            /** Keywords */
            keywords: string[];
        };
        /**
         * QueryIntent
         * @description What the user appears to have typed.
         *
         *     The four intents map onto the four input modes the product promises:
         *     a topic, a keyword, an identifier lookup, or a pasted abstract.
         * @enum {string}
         */
        QueryIntent: "topic" | "keyword" | "identifier" | "abstract_snippet";
        /**
         * RankingReport
         * @description Whether relevance ranking ran, and with what.
         *
         *     Reported for the same reason source failures are: the frontend needs to
         *     tell a user "these results are in retrieval order, not relevance order"
         *     rather than silently presenting a worse list as if it were ranked.
         */
        RankingReport: {
            /** Applied */
            applied: boolean;
            /** Strategy */
            strategy: string | null;
            /** Model */
            model: string | null;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /**
             * Reason
             * @description Why ranking did not run.
             */
            reason: string | null;
        };
        /**
         * RelevanceScore
         * @description Why a paper ranked where it did.
         *
         *     The components are kept alongside the combined score, not discarded,
         *     for two reasons: the UI shows a breakdown rather than an unexplained
         *     number, and an evaluation run can attribute a ranking change to the
         *     signal that caused it.
         */
        RelevanceScore: {
            /**
             * Combined
             * @description Fused score, 0-1, for display.
             */
            combined: number;
            /**
             * Semantic
             * @description Raw cosine similarity of query and paper embeddings.
             */
            semantic: number;
            /**
             * Lexical
             * @description Raw BM25 score, unbounded and corpus-relative.
             */
            lexical: number;
            /**
             * Rank
             * @description 1-based position in the ranked result set.
             */
            rank: number;
            /**
             * Strategy
             * @description Fusion strategy that produced `combined`.
             */
            strategy: string;
        };
        /**
         * SearchRequest
         * @description Inbound search parameters.
         */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit Per Source
             * @default 20
             */
            limit_per_source: number;
            /**
             * Sources
             * @description Restrict the fan-out; defaults to every registered source.
             */
            sources?: components["schemas"]["SourceName"][] | null;
        };
        /**
         * SearchResponse
         * @description Merged, deduplicated results plus the provenance of the fan-out.
         */
        SearchResponse: {
            query: components["schemas"]["ParsedQuery"];
            /** Papers */
            papers: components["schemas"]["Paper"][];
            /** Total */
            total: number;
            /** Sources */
            sources: components["schemas"]["SourceReport"][];
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Duplicates Merged
             * @default 0
             */
            duplicates_merged: number;
            ranking: components["schemas"]["RankingReport"];
            /** Clusters */
            clusters: components["schemas"]["TopicCluster"][];
            clustering: components["schemas"]["ClusteringReport"];
            entities: components["schemas"]["EnrichmentReport"];
            summaries: components["schemas"]["SummaryReport"];
        };
        /** SourceInfo */
        SourceInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * SourceName
         * @description Identifier for an upstream literature provider.
         * @enum {string}
         */
        SourceName: "pubmed" | "arxiv" | "crossref";
        /**
         * SourceReport
         * @description Per-source diagnostics returned alongside every search.
         */
        SourceReport: {
            source: components["schemas"]["SourceName"];
            status: components["schemas"]["SourceStatus"];
            /**
             * Returned
             * @default 0
             */
            returned: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /** Message */
            message: string | null;
        };
        /**
         * SourceStatus
         * @description Outcome of one source's contribution to a fan-out.
         *
         *     The frontend renders these directly: a partial result ("no results from
         *     PubMed, showing arXiv and Crossref only") is a legitimate, informative
         *     state rather than an error.
         * @enum {string}
         */
        SourceStatus: "ok" | "empty" | "timeout" | "rate_limited" | "unavailable" | "parse_error" | "skipped";
        /**
         * Summary
         * @description A paper summary, its provenance, and its grounding verdict.
         */
        Summary: {
            /** Text */
            text: string;
            origin: components["schemas"]["SummaryOrigin"];
            grounding: components["schemas"]["GroundingVerdict"];
            /**
             * Model
             * @description Model or method that produced the text.
             */
            model: string;
            /**
             * Prompt Version
             * @default 1
             */
            prompt_version: number;
            /**
             * Attempts
             * @description Generation attempts made.
             * @default 1
             */
            attempts: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Rejected For
             * @description Why the first attempt was rejected, kept even when a retry rescued it. The final verdict says the text shown is sound; this says what it took to get there.
             */
            rejected_for: components["schemas"]["GroundingIssue"][];
        };
        /**
         * SummaryOrigin
         * @description Where the text a user is reading actually came from.
         * @enum {string}
         */
        SummaryOrigin: "generated" | "regenerated" | "extractive";
        /**
         * SummaryReport
         * @description Per-search summarization diagnostics.
         *
         *     Mirrors the source, ranking and clustering reports: a stage that
         *     degraded must say so rather than leave the UI guessing.
         */
        SummaryReport: {
            /** Applied */
            applied: boolean;
            /** Model */
            model: string | null;
            /**
             * Summarized
             * @default 0
             */
            summarized: number;
            /**
             * From Cache
             * @default 0
             */
            from_cache: number;
            /**
             * Regenerated
             * @description Summaries that needed a second attempt to pass.
             * @default 0
             */
            regenerated: number;
            /**
             * Fell Back
             * @description Summaries that could not be grounded and were replaced.
             * @default 0
             */
            fell_back: number;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /** Reason */
            reason: string | null;
        };
        /**
         * TopicCluster
         * @description One sub-topic within a result set.
         *
         *     ``terms`` is what makes this usable in a UI: a cluster identified only
         *     by a number is no more navigable than the flat list it replaced, so
         *     every cluster carries the terms that distinguish it from its siblings.
         */
        TopicCluster: {
            /** Id */
            id: number;
            /**
             * Label
             * @description Short human-readable name, built from `terms`.
             */
            label: string;
            /**
             * Terms
             * @description Distinctive terms, best first.
             */
            terms: string[];
            /** Paper Ids */
            paper_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                /** @description Topic, keyword, DOI or abstract */
                q: string;
                limit_per_source?: number;
                sources?: components["schemas"]["SourceName"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_post_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_api_parse_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedQuery"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_many_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_one_api_export__paper_id__get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ExportFormat"];
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_formats_api_export_formats_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
        };
    };
}
